### ISSUE TITLE
Quote Post/Best Answer

### ISSUE THREAD

**Issue by Denoder** [Riari/laravel-forum#10]
How would one go about including quotable posts and a best answer post feature?

**Comment by Riari** [comment]
Basic quoting can be implemented in the views using whatever editor/parsing combination you like. Personally I'm using a combination of [lepture/editor](https://github.com/lepture/editor) and markdown parsing, with quoted posts inserted as blockquotes. I've also played around with a BBCode integration, but it really comes down to personal preference. The main thing is that you only need to override the views to achieve that kind of thing.

A best/accepted answer type of feature would require extending the Post model and creating associated forms, controller methods, etc. It's not supported out of the box in any way, but would be possible to implement entirely in your app's namespace without having to touch any of the package files. That said, it's a feature that I'd be interested in introducing as standard (probably with the ability to enable it on a per-forum basis), so any contribution would be welcome.

**Comment by Denoder** [comment]
I dont really know how to implement the quoting + best/accepted answer feature. Normally I would find an example look at how it's done then make my own, or take it from whatever package it's from and integrate it. I usually try to contribute but the way i do things is so random it usually doesnt help. (but i still try)

I basically stripped down your forum package and integrated it into mine :/ so it's no longer a package rather a series of repositories, controllers, and middleware. I removed the forum permission and replaced it with custom roles and permissions.

**Comment by Riari** [comment]
OK, for the quoting thing, I might be able to find some time to show you how I integrated an editor and markdown parsing in my views if that would help. At the very least I can show you some pointers. For the most part we're only talking 3-4 small edits in the views.

For best/accepted answer functionality, I might consider building that into the next minor release. I'll update here if I make any progress with that.

Also, you shouldn't actually need to strip the package down or remove anything - you can extend or modify the forum functionality by overriding the controller and/or extending the models, which is enough for the vast majority of cases (for example, I extended the models in one of my projects to add Recent Threads/Posts to user profiles).

In the case of permissions specifically, the package provides callbacks that you can use to integrate whatever approach you're using for handling permissions. Assuming you're using Laravel 5 and have published the config, you can find those callbacks in `config/forum.permissions.php`. They have defaults, you just need to tweak them.

Beyond that, I'm not really sure how I can help. It sounds like you want to do quite a lot outside of the scope of the features that ship with the package, but most/all of it should be doable entirely within your app source.

**Comment by Denoder** [comment]
Yea i will need help on that quote thing. Right now for the editor i'm using ckeditor.

well i don't really like to download packages that has other "applications" in them. The forum itself is an application, so i just felt like it should be "in" my application as an internal part... so i did it. (Basically I was trying to avoid doing overrides)

**Comment by Riari** [comment]
Re: quoting, no problem, I'll see what I can do. I'll probably put some gists up and link them here.

As for the rest, I'm not really sure what you're getting at. Laravel Forum isn't an application - it won't even do anything by itself. Your application is an application, and this is a package specifically designed to be integrated with such an application. In fact, one of my main goals when I started the project was to provide a forum solution that makes zero assumptions about the app it's being used in, and to only contain features/functionality that tie directly with discussion forums.

That's why there's no quoting feature out of the box; to include one would mean making assumptions about what kind of editor and parsing capabilities you're using, which goes against the philosophy of the package. Of course I could have implemented quoting anyway and made it highly configurable, but as it's relatively simple to implement via the views, I decided it's best left to the discretion of the developer.

You mention that you want to avoid doing overrides, but that's a major aspect of Laravel packages. Most packages are _designed_ to give you ways of overriding and tweaking their behaviour - Laravel itself has tools to facilitate exactly that. [Config overriding](http://laravel.com/docs/5.0/packages#configuration) is probably the most common example.

With that in mind, I'd strongly recommend reconsidering your approach:

If you want to build lots of features/functionality on top of/around a package, or even rewrite it to work exactly how you want it to, just fork it. That's exactly what I did (note the ' forked from atrakeur/laravel-forum' at the top of the page). That way, you have your own maintainable, re-usable version of the package and can even set it up to be pulled into your projects using composer.

Otherwise, just use the package as it's designed, because I don't think you're going to help yourself much in the long run by trying to move it "into" your application - that really defeats the purpose Laravel's extendability. (As a sidenote, even the Laravel framework core itself is a package!)

**Comment by Denoder** [comment]
> _> its too late for me to make it back into a package its pretty much just in there now. I did this because it was a pain in the arse for me to use it in L5 (I literally knew nothing about L5 at the time so i found it easier to just integrate it into the initial application)

**Comment by Riari** [comment]
Well, I would have expected it to be easier to learn how to integrate the package as-is (which is pretty simple given that there are step-by-step instructions), than to try and pull it into your app source (which would require some knowledge of how the package is structured and written).

But if that's how you want to tackle it, I'm not going to stop you!

Closing this now since the original questions have been answered.

**Comment by Riari** [comment]
P.S. about the quoting - I will put gists up if I can find time. But to give you some idea, in your case, you'll need to add a quote button to the [partials/post.blade.php view](https://github.com/Riari/laravel-forum/blob/laravel-5/src/views/partials/post.blade.php) and wrap the post content in a `<div class="content"></div>` (or similar, just to make it easier to identify the content). Then write a JS click event for the quote button that uses the CKEditor API to copy the contents of that div into your CKEditor textarea.

You can instantiate CKEditor on the default textarea in [partials/forms/post.blade.php](https://github.com/Riari/laravel-forum/blob/laravel-5/src/views/partials/forms/post.blade.php) by using it on `textarea.form-control`.
