### ISSUE TITLE
How to integrate this to a laravel projects 

### ISSUE THREAD

**Issue by jerryOkafor** [Riari/laravel-forum#101]
Please I have a project I want to include a forum, it is already crafted and how can I integrate this project easily.

**Comment by Riari** [comment]
It's documented. Specifically, you'll want to follow http://teamteatime.net/docs/laravel-forum/3.x/installation.md and http://teamteatime.net/docs/laravel-forum/3.x/front-end/installation.md to get started.

**Comment by jerryOkafor** [comment]
i have succeeded but one thing is left, the web guard middleware enbles session in laravel 5.2, so when i run /forum i get this errors:

ErrorException in 6829460faf86e4b23bc8a19c8baa92dc4b035c9e.php line 7:
Undefined variable: errors (View: C:\wamp\www\agron\resources\views\vendor\forum\partials\alerts.blade.php) (View: C:\wamp\www\agron\resources\views\vendor\forum\partials\alerts.blade.php) (View: C:\wamp\www\agron\resources\views\vendor\forum\partials\alerts.blade.php)

**Comment by antonkomarev** [comment]
@jerryhanks take a look: #97

**Comment by jerryOkafor** [comment]
This does not explain the errors I am getting, how do I manipulate the forum routes so that they can be validated in the Web middleware

**Comment by antonkomarev** [comment]
Errors you've showed means there is no global errors variables defined.
In Laravel 5.2 it's only exists when you are using `web` middleware group, because `\Illuminate\View\Middleware\ShareErrorsFromSession::class,` was moved from global middlewares to it. 
Try to add for this middleware the test to global ones and check how it works.
