### ISSUE TITLE
MethodNotAllowedHttpException in RouteCollection.php line 219:

### ISSUE THREAD

**Issue by roma1004** [Riari/laravel-forum#107]
hi...! I need your help, this error show me when I generate a pagination,
in my app I build a search-method, when I search a user in my app, and the result are more the 8 user, the app generate a pagination, but when I click en page 2, show me error "MethodNotAllowedHttpException in RouteCollection.php line 219:" .
my code route.php is -> Route::post('search',[ 'as'=>'search','uses'=>'mecontroller@search']);
my form is -> 
<--form action='{{ url("search")}}' method='post'-->
<--input type='hidden' value='{{ csrf_tonken()}}' -->
<--input type='submit' value='Search'-->
<--/form-->
please help.

**Comment by Riari** [comment]
Hi,

General questions about Laravel don't belong here; you should try posting on the [Laracasts forums](https://laracasts.com/discuss) or [laravel.io](http://laravel.io/forum).

I'll leave you with a hint though. The reason you're getting that error is because your search route is defined as a POST route, meaning it will only accept POST requests, whereas clicking your pagination link triggers a GET request. The easiest way to fix this would be to change your route and form to use GET instead of POST, and persist the search query parameter in your pagination links. Look here for an example: https://laracasts.com/discuss/channels/general-discussion/search-results-paginate
