### ISSUE TITLE
Integration with Asgard CMS

### ISSUE THREAD

**Issue by yenerunver** [Riari/laravel-forum#108]
Hi there,

We are trying to implement your forum with Asgard CMS, but having difficulty of getting Asgard Middlewares work with your forum.

It works, but not recognizes us as admins.

Also, the translation files are not working with Asgard.

What do you suggest?

**Comment by Riari** [comment]
Hi,

I don't know what to suggest without trying it myself as I have zero experience using Asgard CMS. I would have expected it to Just Work™ since it's built on Laravel 5, but it sounds like Asgard does a few things differently compared to a vanilla Laravel 5 install.

What does the Asgard-specific Middleware do exactly? And how do its own translations work?

**Comment by yenerunver** [comment]
Asgard uses https://github.com/cartalyst/sentinel, https://github.com/cartalyst/sentry and https://github.com/Maatwebsite/Usher for authentication and https://github.com/dimsav/laravel-translatable for translations.

**Comment by Riari** [comment]
Okay, Sentinel presents a problem. The forum is designed to work with Laravel's built-in authentication and as far as I'm aware, Sentinel replaces that. See issue #62 for more on that.

I see no reason why the translations shouldn't work since they're done in the standard Laravel way, and dimsav/laravel-translatable only seems relevant to models rather than static text.
