### ISSUE TITLE
Multiple User Models

### ISSUE THREAD

**Issue by NicholasSmith753** [Riari/laravel-forum#110]
Hi Riari,

I currently use kbwebs/multiauth to allow my Laravel 5.1 application to support multi-user authorization. Is there a way to allow the user model attribute of the forum package to support multiple models such as using an array?

**Comment by Riari** [comment]
That's a tricky one. It will work with a "user" auth type if you have one defined in multi-auth, since that would match any calls to `Auth::user()`, but it would only work with that.

Prior to 3.x, there was a callback in the config that could be used to return the current user object - see [here](https://github.com/Riari/laravel-forum/blob/laravel-5/src/config/integration.php#L37). I think that would give you enough flexibility to completely integrate multi-auth with the forum. If you're interested, I might consider bringing that feature back for the next version. :)

**Comment by NicholasSmith753** [comment]
I see, yes I would definitely be interested. So the current_user callback would always return the model of the currently logged in user without any additional changes to its implementation? Or would I need to test for the model type using an if nest?

Also, when would the next version be available?

**Comment by Riari** [comment]
Basically, yes - but it would be a method in the front-end utility class rather than a callback in the configuration (they were all removed to make the config cache-friendly). Details on the utility class can be found [here](http://teamteatime.net/docs/laravel-forum/3.x/front-end/helpers.md).

Not sure when the next release will be as I need to review the other issues and make a decision about that, but I'll do that this week so hopefully very soon :)

**Comment by NicholasSmith753** [comment]
Actually, I am here looking at the source code for another package and I will have the same problem with it as well. It makes me feel like I am going against the grain by using separate tables for my user types. Is the correct way to use the Users table and model as a centralized authentication table in Laravel? 

If so, it would make more sense for me to bite the bullet now and change to using the Users table to make my application more compatible with other packages because it would be ridiculous to expect a patch just for my app each time I hit a snag.

**Comment by Riari** [comment]
I wouldn't say there's a correct way per se - there are legitimate reasons to have multiple user tables. But if you have no particular need for it, then yes, it's probably more hassle than it's worth :)

Sounds like what you might need is some kind of user group/role system. There are quite a few packages covering that area and it's easy enough to implement user roles using models: https://laracasts.com/lessons/users-and-roles

**Comment by NicholasSmith753** [comment]
Hi Riari,

I will try using the roles and profiles approach to build my app's user authentication. Thanks.
