### ISSUE TITLE
Forum-Frontend Navigation Error

### ISSUE THREAD

**Issue by NicholasSmith753** [Riari/laravel-forum#112]
Hi Riari,

I tried setting up a Laravel 5.2 vanilla installation to test the laravel-forum. I used the new make:auth artisan command to quickly set up the user Auth system and create a new user. After successful authentication and navigation to the /forum route I receive this error:

ErrorException in 115a1f5332556ab426389dc331d09b0d30856cdf.php line 7: Undefined variable: errors (View: D:\Dropbox\Web-Server\web-content\LDS\ResearchProject\buildtest52\build\resources\views\vendor\forum\partials\alerts.blade.php) (View: D:\Dropbox\Web-Server\web-content\LDS\ResearchProject\buildtest52\build\resources\views\vendor\forum\partials\alerts.blade.php) (View: D:\Dropbox\Web-Server\web-content\LDS\ResearchProject\buildtest52\build\resources\views\vendor\forum\partials\alerts.blade.php)

After doing a little digging I realized that the index() method on the CategoryController in the forum-frontend really didn't seem to pass an errors array/object which causes the partials/alerts.blade.php to throw an error.

Can you guide me on the best way to correct this problem?

**Comment by Riari** [comment]
Hi,

Yes, all you need to do is apply the `web` middleware using the [middleware config option in the frontend](https://github.com/Riari/laravel-forum-frontend/blob/1.0/config/frontend.php#L45). See issue #97 for details.

I'll be updating the docs and readme with compatibility notes to cover this soon - or I may find a way to automate it so that the `web` middleware is always applied in addition to whatever the config is set to.

**Comment by NicholasSmith753** [comment]
Oh yes, that worked really well. Thanks a lot!
