### ISSUE TITLE
How can I run the forum , I have integrated it with my laravel project

### ISSUE THREAD

**Issue by aksuhana** [Riari/laravel-forum#127]

**Comment by Gummibeer** [comment]
Can pls give us some mor einformations? What do you mean with "How can I run the forum"?
- Do you mean how you can get a frontend? : https://github.com/Riari/laravel-forum-frontend
- Do you mean how to configure it? : https://github.com/Riari/laravel-forum#configuration
- Do you mean how to use it an API-way? : use the given routes, to find out more how to coll them you can search the source code of this package or for usage-examples in php you can search the frontend packages source code

If you need help for something else we need more informations.

**Comment by aksuhana** [comment]
ya , I follow the all steps to integrate the forum , I also use frontend: https://github.com/Riari/laravel-forum-frontend . But how can I get access to the page so that I can view the forum page. I mean Which url should I hit. I tried with localhost:8000/forum, but only index , Index  is showing , from where I can comment and view those comment. What should I  to do?

**Comment by Gummibeer** [comment]
If you have all the views of the frontend package tehre should be all buttons to create new threads, comments and so on. If there is no create button for categories and there is no category you can check the policy classes and/or create categories by migration or seed.

**Comment by ann3018** [comment]
For the same issue ,i am getting the following error in my view , when i am hitting localhost:8000/forum

**Undefined variable: errors**

in detail

ErrorException in 31ab8b6187194eed5da519f43ee34f3af905ccae.php line 7:
Undefined variable: errors (View: C:\wamp64\www\education_portal\vendor\riari\laravel-forum-frontend\views\partials\alerts.blade.php) (View: C:\wamp64\www\education_portal\vendor\riari\laravel-forum-frontend\views\partials\alerts.blade.php) (View: C:\wamp64\www\education_portal\vendor\riari\laravel-forum-frontend\views\partials\alerts.blade.php)

**Comment by Gummibeer** [comment]
Do you have the right versions? There was a change in the frontend package I think. :/

**Comment by Riari** [comment]
@ann3018 That is a separate issue, you need to set your `forum.frontend.middleware` config to `web`.

**Comment by aksuhana** [comment]
i

**Comment by ann3018** [comment]
thanks  ! I got it . But there is a page while hitting localhost:8000/forum  which shows 

index (with clickable link)

Index

but in demo page I look a various thread , May You please help me out for this what I need to do so that I can view all the thread on particaular url or may u provide me a related example. As in your previous comment you have described  about buttons and category . and I have all the views from where I can generate a buttons or etc.

**Comment by Riari** [comment]
There's documentation, please use it :) http://teamteatime.net/docs/laravel-forum/3.x/front-end/management.md

If you're logged in and don't see any option to create categories, you're probably using a third party authentication package that the forum isn't compatible with. Otherwise, you should see the option, just like you do on the demo when logged in as Admin.

Note that the default policies allow anyone to create categories, so you'll want to override the Forum policy to change that. See http://teamteatime.net/docs/laravel-forum/3.x/policies.md

**Comment by Gummibeer** [comment]
https://github.com/Riari/laravel-forum-frontend/blob/1.0/views/category/index.blade.php
For example in this view (L5 - L7) the ability to create a Category is checked and if the user can create one the form to create one get's displayed.
This is the initial forum index view. If this isn't there something is wrong in your setup (custom routes, controller, views or something like this).

**Comment by ann3018** [comment]
Thank You So Much ! I am finally able to do what I need . Thanks Again for your great support.

**Comment by Riari** [comment]
No problem, glad we could help :)

**Comment by dannymichel** [comment]
is there a demo?

**Comment by Riari** [comment]
Yes: http://laravel-forum.teamteatime.net/
