### ISSUE TITLE
Undefined index: Post

### ISSUE THREAD

**Issue by ronnievisser** [Riari/laravel-forum#134]
Hi,

Since yesterday the following error occurs.

Undefined index: Post (View: /home/vagrant/Code/Personal/PHP/Soccerrama/resources/views/vendor/forum/category/partials/list.blade.php) (View: /home/vagrant/Code/Personal/PHP/Soccerrama/resources/views/vendor/forum/category/partials/list.blade.php) in /vendor/riari/laravel-forum/src/Support/Traits/CachesData.php:22

Can you please asap.

**Comment by Riari** [comment]
Hi,

This is due to the addition of a 'Post' array key in `forum.preferences.cache_lifetimes`. Unfortunately it seems that config merging isn't recursive, so anyone who's already overridden that config file will need to update it. Here's what you need to add: https://github.com/Riari/laravel-forum/blob/3.0/config/preferences.php#L52

Thanks

Edit: I'm going to work on a new release today that will make it fall back to the 'default' value in case of missing keys in that array.

**Comment by ronnievisser** [comment]
Thanks!

**Comment by Riari** [comment]
No problem :) I've just pushed a release to fix this already: https://github.com/Riari/laravel-forum/releases/tag/3.1.1
