### ISSUE TITLE
authorName is null in threads

### ISSUE THREAD

**Issue by aenciso** [Riari/laravel-forum#138]
I am using a standard Laravel 5 users table plus some extra fields.
If I change the default setting to  'user_name' => 'username' in forum.integration.php it doesn't display any author name in threads.

**Comment by Riari** [comment]
I assume you have either a `username` column, or a `getUserAttribute()` method, or both?

**Comment by aenciso** [comment]
Hi,

I have only a 'username' column. Do I need a getUserAttribute() method as well?

Thanks

**Comment by Riari** [comment]
No, it should work with the column by itself. Not sure why this isn't working for you. The relevant code is here: https://github.com/Riari/laravel-forum/blob/3.0/src/Models/Traits/HasAuthor.php#L20

In the views (take post/partials/list for instance), what happens if you change `$post->authorName` to `$post->author->username`?

**Comment by aenciso** [comment]
No worries, it was a spelling mistake. It works perfect.

Thanks for your quick reply.

**Comment by Riari** [comment]
No problem :)
