### ISSUE TITLE
Forum Input Errors showing up as dumped code.

### ISSUE THREAD

**Issue by Keirul** [Riari/laravel-forum#149]
Whenever I get an error in the forum I get the errors as a var_dump.
`{"error":"The submitted data did not pass validation.","validation_errors":{"content":["The content must be at least 5 characters."]}}``

So a blank page with an error like the example above.
http://prntscr.com/cjqrr1

**Comment by Riari** [comment]
Is this on a Laravel 5.3 app?

**Comment by ronnievisser** [comment]
yes 5.3. I have the same issues. also new threads submit fails and then break overview.

**Comment by Riari** [comment]
OK, sorry about this. This is what I get for not having tests :) I'll investigate and push a fixed release ASAP.

**Comment by Riari** [comment]
I've pushed a change to a new branch that should fix the issue. Can one of you confirm that this works for you please? https://github.com/Riari/laravel-forum/tree/4.0

**Comment by Riari** [comment]
Fixed in [4.0.0](https://github.com/Riari/laravel-forum/releases/tag/4.0.0). The major version bump is necessary because the difference in the way validation is handled in 5.3 caused this breakage and I was unable to find a solution that worked well for both 5.3 and prior Laravel versions, so to ensure compatibility with 5.3 and beyond, you'll need to change your composer dependency to pull in `~4.0` instead of `~3.0`.
