### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Screpuh** [Riari/laravel-forum#150]
After an update i'm getting the following error:

PHP Parse error:  syntax error, unexpected '.', expecting ',' or ';' in vendor/riari/laravel-forum/src/ForumServiceProvider.php on line 23

Any idea what could be the problem here?

**Comment by Riari** [comment]
What's your PHP version?

**Comment by Screpuh** [comment]
PHP 5.5.9. I will try updating to PHP 7..

**Comment by Screpuh** [comment]
Sorry, my bad. This fixed the issue.. Thanks for the fast response!

**Comment by Riari** [comment]
No problem, glad you got it fixed. Curious if this is an issue with a specific PHP version though, since it's supposed to be compatible with 5.4+. Can you clarify what you did to fix it?

**Comment by Screpuh** [comment]
Hmm don't know for sure if it was the issue.. but I just update PHP to the latest version (PHP 7.0.11) and now the error is gone :)

**Comment by Riari** [comment]
OK, thanks for the info. 👍

**Comment by mydnic** [comment]
@Riari I would like to reopen this one because I have the same error.. I upgraded the packages on my digitalocean server and I got this error.
I tried to upgrade to PHP7 but it didn't solve the error..

**Comment by Riari** [comment]
OK, upgrading to PHP 7 should actually fix it because it seems that 5.6 and above does in fact support concatenation for class constants, but since the package is supposed to be compatible with 5.4 and above, I have simply turned the constant in question into a method instead. The latest releases include this change. 👍
