### ISSUE TITLE
Thread view count

### ISSUE THREAD

**Issue by garygreen** [Riari/laravel-forum#152]
Would be nice to store number of unique views for given thread. I believe most forums determine unique view by ip.

**Comment by Riari** [comment]
I looked into this when I first implemented the view count and was unable to figure out a solution that would satisfy most use cases at the time. If I change this, it'll most likely be in the form of some utility methods that determine whether or not to count a view for a given model (and user, if authenticated).

Any suggestions would be welcome, but essentially I don't want to make this the default behaviour.

Thanks!

**Comment by garygreen** [comment]
Thanks for your quick reply. I agree it is difficult having a solution that works for all. However pretty much all forums have a view count which is very important to gauge the popularity of threads etc.

Maybe implement some 'sane default' manner for counting the number of views for a thread with an option to use your own class/closure/events or whatever that can count the threads in a custom way. I suspect most people would be happy with the default way though, assuming it makes sense. 😄

**Comment by Riari** [comment]
That's actually not true - most forums _don't_ check for uniqueness when incrementing view counts, they'll just increment it for every view regardless of the viewer. That's how many major forum platforms work, even - phpbb3, vBulletin 4 and IPB (to name a few) all do this by default.

I would argue that it makes sense this way because of the following reasons:
- A view is a view - granted, a user refreshing the page probably shouldn't increase it, but arguably it makes sense if the user later returns to the thread when it contains new posts.
- Its accuracy isn't crucial, it's just an indication. If the forum owners require accurate analytics, they should use an analytics solution designed for that purpose. For users, it doesn't really matter so much (especially as the exposure of a thread is not determined by view count. It's just a number).

Because of that, the way it works now will remain the default, but I'm absolutely not adverse to the suggestion of making it customisable behaviour. What I have in mind is an overridable method that accepts `$thread` and `$user` parameters and returns a bool to indicate whether or not the view should be counted. By default, it'll always return true. You can use it to control the behaviour in just about any way you like - "cooldown" between views, uniqueness by IP or user ID, different behaviour for guests, etc.

Not sure when I'll get around to this, but I'll make it a priority. I think I can get something implemented by the end of next week. Thanks for your input!

**Comment by garygreen** [comment]
Thanks for your detailed comment. I didn't realise most forums worked like that, the ones I have used must have some kind of cooldown because if I refresh it doesn't count as a view. Maybe there could be two flavours; an instant counter that counts every hit to that thread, or one where it will count a hit and add to the cache a certain (configurable) cooldown time. That would probably suit most people, though like you say if people would like to implement their own method that returns if a view should be counted, that would be cool as well.

**Comment by garygreen** [comment]
Oh and no rush man, it's just something I thought I'd make a suggestion on 😄 

Nice package you have here. We're looking to convert a forum system that is currently in Vanilla Forum to this so just weighing up how long it'll likely take, does it have all the features we need etc. I think the views and converting the existing data will be most time consuming, hoping I can use the laravel-frontend base and do some theming, I don't really want to be copying and pasting forms and stuff in case it breaks/changes in later releases.

**Comment by Riari** [comment]
Many of them do cache, yeah, just not necessarily with a cooldown. I made a point of visiting a few large forums just before I implemented stats in this package to see how they handled thread views and found that I could refresh a thread X times and see the count bump up by that number 5 minutes or so later.

That kind of caching doesn't apply so much here since the counts were moved to the thread table itself, but in any case, I think a simple bool-returning `shouldViewCount($thread, $user)` will be enough to satisfy most (if not all) cases :) it won't take much to introduce that, I just need to decide where it should go since there is no suitable place for it currently. It might just mean introducing a `Util` class as per the frontend package.

And thanks, glad you like it so far! If you need a hand with anything, I'm on Larachat most days. Feel free to DM me on there with any questions you might have.
