### ISSUE TITLE
How to get latest posts URL's

### ISSUE THREAD

**Issue by rtfmfm** [Riari/laravel-forum#161]
Hi! I'm trying to list N recently updated threads from the forum in the laravel view but I'm unable to get the URL of the post. Can you help me with this?

Thank you in advance!

**Comment by Riari** [comment]
Hi,

If you're using 3.x or 4.x, you can do this using model instances and the `Forum::route()` helper method (detailed here: http://teamteatime.net/docs/laravel-forum/3.x/front-end/helpers.md).

To obtain the model instances, you have two options:

1. Query for them via Eloquent as you would normally; however, this omits the usual permission checks, so you'd need to do those manually
2. Query for them via the `GET /api/thread/new` endpoint, which takes care of permission checks automatically

To give an example of the first option, if you wanted to render links to the 5 most recent thread replies, you'd do something similar to this:

```
$posts = \Riari\Forum\Post::where('post_id', '!=', null)
    ->orderBy('created_at', 'desc')
    ->limit(100)
    ->get()
    ->filter(function ($post) use ($request) {
        return !$post->thread->category->private || Auth::check() && $request->user()->can('view', $post->thread->category);
    })->take(5);
```

(Note the higher limit to ensure there's enough threads to pick from after 'non-visible' threads are filtered out)

Then in a Blade View, render them like this:

```
<ul>
    @foreach ($posts as $post)
        <li>
            Re: <a href="{{ Forum::route('thread.show', $post) }}">
                {{ $post->thread->title }}
            </a>
            by {{ $post->author->name }}
            <br>
            {{ $post->created_at->diffForHumans() }}
        </li>
    @endforeach
</ul>
```

I hope that helps. I'll leave this open in case you have any further questions, otherwise feel free to close it :)

**Comment by rtfmfm** [comment]
Thank you, Sir! It works perfect (Laravel 5.3 / laravel-forum ~4.0)!
I'm happy to find out that this great package is so well maintained!

The next thing I need is to implement "thread subscription system". I'll add table in the database and a button in the view, but I'll need your help for information how to modify the controller without changing anything in the vendor folder (because all your controllers are in vendor as you know ;-)). I'll create another issue for this if it's not a problem.

Thank you again!

**Comment by Riari** [comment]
No problem, glad to help. 👍
