### ISSUE TITLE
[Feature] Thread moving & title editing

### ISSUE THREAD

**Issue by Denoder** [Riari/laravel-forum#17]
Can you add the ability to move threads to different categories and Edit thread titles cause sometimes someone makes a mistake and there isnt a way to edit the title besides the db)

**Comment by Riari** [comment]
Thread moving is on my list; thread title editing isn't something I considered but I'll definitely add that too.

No ETA yet as I've only just finished tweaking thread view counting and would like to introduce more events in the near future.

**Comment by Denoder** [comment]
i made my own version of the view counter for threads. Now it has throttling so views doing immediately go up as so as you refresh, its all based on sessions.

**Comment by Riari** [comment]
That's pretty much exactly what I did. Take a look at the 2.4.0 commit: https://github.com/Riari/laravel-forum/commit/88b02e749c164140edc2f0f8dc680cced52c0c49

**Comment by Denoder** [comment]
coolio, however i needed to adapt this to other models so i cant use that one >_>

**Comment by Riari** [comment]
Fair enough. In the future, once there are events covering all of the main actions/routes, I'll probably move more of this functionality into a default set of event handlers that can then be individually overridden or disabled.

**Comment by Riari** [comment]
By the way, I don't think throttling means what you think it means - because it certainly wouldn't make "views immediately go up as you refresh" :P

Anyway, I've added your feature requests [to the wiki](https://github.com/Riari/laravel-forum/wiki/Features#planned-features--improvements) and may update here when I make progress.

**Comment by Denoder** [comment]
here's a snapshot of what im currently doing with the forum package :3 - ![Design](http://i.imgur.com/whtRf14.png)

**Comment by Riari** [comment]
Nice work. It's great to see how it's being used :)

**Comment by Denoder** [comment]
Ill get more screenshots in once i figure out how to connect the post author to user roles >_>

**Comment by Riari** [comment]
If you do want to share more screenshots, could you submit them in a separate issue? I might expand the wiki to feature screenshots demonstrating how it can look with some customisation.

About the post author and user roles, I'm not sure exactly what you're trying to do but user roles should be accessible directly from your user model, e.g. `$thread->author->roles`.

**Comment by Denoder** [comment]
I'm using Laravel Boilerplate located:
https://github.com/rappasoft/laravel-5-boilerplate

so its a bit different. If you can check it out you will see what i mean. (The models are in the app folder)

**Comment by Denoder** [comment]
did u take a look cause im a bit confused on it >_>

**Comment by Riari** [comment]
I did. There's nothing unusual about the models being in the app directory - that's standard for Laravel 5 as they were moved out of the models directory due to the old structure supposedly being too suggestive of a strict MVC architecture.

In my L5 projects I actually move the models back into app/Models

Apart from that, I don't see anything particularly unusual about that project. If you're stuck on trying to integrate a specific thing with the forum, feel free to open an issue for it.

I'll close this one for now since we're off-topic.
