### ISSUE TITLE
View post button showing 404(page not found) error for the deleted post on thread detail page

### ISSUE THREAD

**Issue by hardiktailored** [Riari/laravel-forum#177]
As author when you delete the post, it will still list in thread posts with deleted tag but without Edit button on left and Reply button on right but will show View post button. 
When you click on View post button on right side, it will show "page not found(404)" error.
It should open with all the post content and replies and it should have options to restore or permanent delete(for permitted user only) like it shows after checking check-box on thread post listing page itself.

**Comment by Riari** [comment]
I'm not convinced that this should be changed. It makes sense that a 404 is returned for a deleted post because the request is specifically for that post - and in a thread context, displaying messages in place of deleted posts is only meant to indicate where in the discussion a post used to exist.

Edit: forgot to add, the View Post button shouldn't be visible in that case, so I'll change the default view in the frontend.

**Comment by Riari** [comment]
Frontend updated.
