### ISSUE TITLE
[Feature] Multi-thread/post delete

### ISSUE THREAD

**Issue by Denoder** [Riari/laravel-forum#20]
How bout we have a way to delete multiple threads and multiple posts?
I think thats very benefitting and provides a quicker way to delete things when there tends to be multiple threads and posts that consists of spam.

**Comment by Riari** [comment]
Yeah, that would be a very worthwhile addition. Eventually I want to expand the administrative/mod tools to make certain actions possible in bulk - deleting posts and deleting or moving threads are the first things that come to mind.

I'll add this to the planned features. If you can think of any other "mass management" type of actions, please do share. Thanks.

**Comment by Denoder** [comment]
Im actually trying to make it myself so ill definitely share the code when i find a solution.
I think those that u mentioned are the basic core functions of a forum.

Any other mass assignable function would have to be integrated with users cause all i can think of is mass assignment of posts to a specific user or the other way around.

**Comment by Riari** [comment]
Changing thread/post author isn't a problem as it only needs to deal with the user ID. The problem would be adding features that warrant any kind of dedicated interface, like a moderator or admin panel. That's the kind of thing that I would expect developers to build into their own (existing) interfaces as I feel it's too opinionated to include by default.

That said, eventually I'd like it to be in a state that enables extensions to be written (as packages) so that kind of thing could be readily available but optional.

Anyway, I'm going to try and do some major (though backwards-compatible) re-writing of the package today to get the events fleshed out and hopefully move permission handling to middleware - maybe I'll add this stuff while I'm at it.

**Comment by Denoder** [comment]
<_< on an unrelated note: I switched from bootstrap to materializecss
But yea i get what you mean, oh  laravel 5.1 changed their cipher options.

**Comment by Riari** [comment]
Glad you mentioned 5.1 actually, it's very close now and I should probably refactor alongside that. I started a new branch for this in case you want to follow the changes: [l5-refactor](https://github.com/Riari/laravel-forum/tree/l5-refactor).

**Comment by Denoder** [comment]
Idk if this counts but how about subscribing to forum(s) to receive email alerts?

**Comment by Riari** [comment]
That falls outside the scope of the package as it's really something that could be very easily facilitated by another package, especially once events have been added to cover posting in threads/categories. Not only that, but subscribing to content is something that often applies to non-forum content, so ideally for most people I'd expect it to be a general purpose implementation.

Not sure if any packages exist that provide a good base for that, at least for Laravel 5, so I might look into writing one.
