### ISSUE TITLE
[Need Help] Profile card implementation

### ISSUE THREAD

**Issue by Denoder** [Riari/laravel-forum#22]
I need help implementing profile cards upon hovering over a user's name.

**Comment by Riari** [comment]
Sorry, I've been away for a few days.

I won't go into much detail regarding this since it depends a lot on how exactly you want it to work, but to give you an idea, in one of my projects I have an "AJAX cards" route group defined like so:

```
Route::group(['prefix' => 'ajax/cards'], function()
{
    get('user/{id}', ['as' => 'ajax.cards.user', 'uses' => 'AJAXCardsController@getUser']);
});
```

The methods in your card controller should just return a view containing only the markup you want to display inside the card. In my case, I have a 'cards' directory to contain a base card view and content-type specific views that extend the base.

In my page views, I use data attributes on the links like so:

```
by <a href="{{ $subcategory->latestActiveThread->lastPost->author->route }}" data-card="{{ URL::route( 'ajax.cards.user', $subcategory->latestActiveThread->lastPost->author->id ) }}">{{ $subcategory->latestActiveThread->lastPost->authorName }}</a>
```

And then I have JS that essentially does the following (using jQuery):
1. On DOM ready, enumerates all of the `a[data-card]` links in the page, caching their respective jQuery objects into an array.
2. On hover event for data-card links, if it's being hovered on for the first time since the page was loaded, append a div to the body with an ID formatted like `ajax-card-<numeric index from the array created in the first step>` and load its content using the URL specified in the data-card attribute, then show it/fade it in. Otherwise, if it was hovered on previously, the div should already exist, so just show it.
3. Hide the card only when the mouse leaves it and the link that triggered it.

Unfortunately I can't give you the actual JS I wrote for this as it's from a private project that is still under development, but I can provide some examples if you need them.

The rest is just CSS for the positioning and style of the cards. Here's how it looks in my project (not a complete example as the card content is under development):

![screen shot 2015-06-14 at 20 55 58](https://cloud.githubusercontent.com/assets/3583774/8150363/88cb8fda-12de-11e5-85b9-d4d8990e5bbe.png)

Edit: needless to say this also doesn't go into caching card content server-side. 95% of this isn't specific to laravel-forum and how you cache card content, if at all, is up to you.

**Comment by Denoder** [comment]
i know nothing about ajax or javascript >_>

**Comment by Riari** [comment]
Okay, in that case I can't really help you without providing a complete implementation and I don't have the time to be doing that. I recommend trying this: http://designwithpc.com/plugins/hovercard

There are code samples on that page telling you exactly how to integrate the plugin after you've included it. You should be able to combine it with the route group, controller and views I mentioned.

**Comment by Denoder** [comment]
there we go, that just what i need. I don't usually make things from scratch. But rather i use other things to help me and build upon that. I dont know a lot about javascript and ajax, but if i'm given something to start with like that link then i can adapt. So thx.
