### ISSUE TITLE
How enable embed YouTube video in posts?

### ISSUE THREAD

**Issue by NDanilov2015** [Riari/laravel-forum#246]
Hi! How I can enable embedding video inside posts, by such code:

<iframe width="315" height="560" src="https://www.youtube.com/embed/p_BRjdV-I8k" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

or may be by simple https://youtu.be/p_BRjdV-I8k

Now iframes and even simple links not shows, I see code as plain text, not video which I wanted insert.

**Comment by NDanilov2015** [comment]
PS. Additional info:

/resources/views/vendor/forum/post/partials/list.blade.php contains such calling:

{!! Forum::render($post->content) !!}

and Forum helper contains: 

public static function render($content)
{
    return nl2br(e($content));
}

if I remove e() function from here method of Forum::helper, I get video - but this is danger. How modify render() function of Forum:: helper to enable Youtube video by links or in iframes and keep yet blocking danger code which hackers can insert?

**rather, instead of editing the vendor file, I found that I can edit the overridden method in app/Support/Forum.php file which not will re-written if I update your Vendor package!

**Comment by Riari** [comment]
It's really up to you to decide how you want to handle this, since it's a very subjective feature that can be handled in a variety of ways (both in terms of editor/UI and the content format used).

Usually for embedding rich media, you would not accept raw HTML from the user but instead use an intermediary format such as bbcode. If you want to do this, your best option would probably be to override the endpoints for creating threads and posts so you can modify the `content` field of the request, then use [internal dispatching](https://www.teamteatime.net/docs/laravel-forum/4.x/api/internal-dispatching/) to forward the request to the API.
