### ISSUE TITLE
Problems with Gates

### ISSUE THREAD

**Issue by alexsweb** [Riari/laravel-forum#270]
Hi there, I have a problem with this, I installed it in a new laravel app and I don't have access to Lock, Pin, Move, I can access the Manage menu and create sections, but that's it.
How can I set the access for the roles?

**Comment by Riari** [comment]
Hi,

Have you overridden any of the policy methods? If not, that's where you need to start and you can find more details about that in the docs: https://www.teamteatime.net/docs/laravel-forum/5/policies/

Regarding roles specifically, it's up to you to decide how to integrate role-based permission checks via the policies because role systems can vary a lot between projects.
