### ISSUE TITLE
Add WYSIWYG

### ISSUE THREAD

**Issue by somato-tomato** [Riari/laravel-forum#275]
Can i add WYSIWYG to thread create ?

Thank you!

**Comment by Riari** [comment]
WYSIWYG is not provided by the package, but you're free to implement it yourself. If you'd like to do that, I would suggest applying your choice of WYSIWYG editor to the textareas in the following views:

- [thread.create](https://github.com/Team-Tea-Time/laravel-forum/blob/5.0/views/thread/create.blade.php)
- [post.create](https://github.com/Team-Tea-Time/laravel-forum/blob/5.0/views/post/create.blade.php)
- [post.edit](https://github.com/Team-Tea-Time/laravel-forum/blob/5.0/views/post/edit.blade.php)

Keep in mind that regardless of your WYSIWYG editor choice, you need to take care not to allow any malicious code in posts, so you should sanitise post content either before it's inserted into the DB (preferable) or before it's used in the frontend. 

By default, the [Forum::render(string $content) utility method](https://github.com/Team-Tea-Time/laravel-forum/blob/84fd702573f460d3b92acbad0f4641f2f3fb9fa6/src/Support/Web/Forum.php#L24) is used to prepare post content for display and strips HTML from it. In order to display a post with any kind of formatting or rich content, you need to let at least a subset of HTML through, so you'll need to either modify the `post.partials.list` view to render post content with your own method, or override the existing method in your own implementation of the `Forum` class. If you choose to do the latter, you can point the package to your own implementation of the class by changing the [`forum.web.utility_class`](https://github.com/Team-Tea-Time/laravel-forum/blob/5.0/config/web.php#L69) config option.

Depending on the WYSIWYG format you choose, you'll probably also want to write post content to the DB in two formats:

- Your WYSIWYG format (e.g. BBCode or Markdown), so you can load it into the editor whenever the post is edited
- Sanitised HTML, so you can display post content without having to convert it to HTML every time a thread/post is viewed

To do this, I would recommend these steps:

1. Create a migration to add a `content_html` column to the `forum_posts` table
2. Implement listeners for the `UserCreatedPost` and `UserUpdatedPost` events provided by the package (see [package events](https://www.teamteatime.net/docs/laravel-forum/5/web/events/) and the [Event Listeners](https://laravel.com/docs/8.x/events#defining-listeners) Laravel documentation) **OR** implement an [Eloquent Observer](https://laravel.com/docs/8.x/eloquent#observers) on the [Post](https://github.com/Team-Tea-Time/laravel-forum/blob/5.0/src/Models/Post.php) model to react to the `saving` event
3. In your listeners or observer, sanitise the post content (which should be in your WYSIWYG editor format) and convert it to HTML, then write it to the `content_html` column for the corresponding post (this should be slightly more efficient if you use the Observer approach as you should be able to simply assign to `$post->content_html` so it gets included in the standard INSERT/UPDATE query)
4. Modify the `post.partials.list` view to make it use `$post->content_html` instead of `$post->content` (see https://github.com/Team-Tea-Time/laravel-forum/blob/5.0/views/post/partials/list.blade.php#L34-L39)

Once that's done, the `content` column will be used for the raw content, which will be used by your WYSIWYG editor in the [post.edit](https://github.com/Team-Tea-Time/laravel-forum/blob/5.0/views/post/edit.blade.php) view.

---

I hope that helps. Remember to refer to the [package docs](https://www.teamteatime.net/docs/laravel-forum/5/) for details about available features.

**Comment by Riari** [comment]
Updated my reply to hopefully make it clearer and put more emphasis on security considerations.
