### ISSUE TITLE
Array to String Conversion Error Present via PHP 7

### ISSUE THREAD

**Issue by Denoder** [Riari/laravel-forum#29]
this is what i currently see when upgrading to PHP7
![Image](http://i.imgur.com/rWOyjcZ.png)

Specifically it has to deal with this line:

```
$this->collections[$model] = $this->$map_model_repos[$model]->getByID($id, $with);
```

would you have any idea on how to fix this?

**Comment by flamerohr** [comment]
The name $map_model_repos sounds like an array... maybe correct it with:

``` php
$this->collections[$model] = $map_model_repos[$model]->getByID($id, $with);
```

Edit: just looked at the controller, removed `$this->` altogether

**Comment by Riari** [comment]
That won't work - `$map_model_repos` is an array containing strings that refer to the protected properties on the class, so for instance `$this->$map_model_repos[$model]` would translate to `$this->categories` where `$model = 'category'`.

This seems to be due to a change specifically in PHP 7, which I'll check out when I can, but in the meantime if you find a solution, please share.

P.S. That part of the controller is going to be changed/removed in the new version I'm working on as the way it works currently is a bit crude.

**Comment by Riari** [comment]
Also, @Teranode, it looks like you're using a modified controller? The line numbers in your stack trace don't correspond logically to the current laravel-5 controller.

**Comment by Denoder** [comment]
Yea i'ts different, I added some more functions for backend features like category management and thread management and such.

---

Yea i've been testing for about 3 hours now but everything I do either breaks the forum or a thread.

**Comment by Denoder** [comment]
when do you think the new one ur working on will be released?

**Comment by Riari** [comment]
I'm not sure. My time is very limited currently, but I'd like to get a working version ready by the end of next month at least.

Could you post your customised controller please? Throw it in a gist (if you haven't used it before: https://gist.github.com/)

**Comment by Denoder** [comment]
https://gist.github.com/Teranode/a20f808a38856b0927fb

**Comment by Denoder** [comment]
already using your refactor modifications, its working great except the
reader status is giving off a 503 service error in php 7

**Comment by Riari** [comment]
Awesome. Yeah, it's under heavy development so there will be lots of breakage for a while.

Even with the first versioned release, there will be some manual upgrading from 2.x.x - but I'll write an upgrade guide in the wiki for that.

**Comment by Denoder** [comment]
> _> now to wait for thread submissions.

**Comment by Riari** [comment]
You're in luck, I just pushed a change set that includes thread creation.

I assume you're just playing with it to get some idea of the differences though, because there's a long way to go yet. Don't expect it to be suitable for production for at least another month.

On topic, I don't think I'll be implementing a fix for PHP 7 compatibility in version 2, mainly because I'm still not sure what the cause is. Version 3 should definitely be compatible though (I don't see any reason why it won't be).

**Comment by Denoder** [comment]
gonna play with it a little more. Gonna try out the dev version of laravel 5.1 to see if that would do anything (since they did include some compatibility changes to it for PHP 7 and its throwable errors)

**Comment by ato10** [comment]
you can use 

``` php
$this->collections[$model] = $this->{$map_model_repos[$model]}->getByID($id, $with);
```

**Comment by Riari** [comment]
Thanks @ato10.

**Comment by jartaud** [comment]
Works great @ato10. Thank you!
