### ISSUE TITLE
Demo is offline

### ISSUE THREAD

**Issue by yormy** [Riari/laravel-forum#298]
your demo is offline at ttps://laravel-forum.teamteatime.net/

**Comment by Riari** [comment]
Hi - thanks for reporting this. It looks like it was caused by a thread titled "ホゲあ" since the slugify function used for generating category and thread URLs doesn't support unicode, so it was ending up with an empty string where the slug parameter in the route is expected.

This is mentioned in the docs, but I'll consider rewriting the function to improve it.
