### ISSUE TITLE
Subcategory's subcategory's thread

### ISSUE THREAD

**Issue by Denoder** [Riari/laravel-forum#31]
I have a slight problem, what if I want to show the lastest active thread on the index fom a subcategory's subcategory?
(This means the nested level is 2)

It would show when im "in" the subcategory but not on the front page.

**Comment by Riari** [comment]
In `thread.blade.php`, something like:

```
@foreach ($category->subcategories as $subcategory)
    @foreach ($subcategory->subcategories as $subsubcategory)
        @foreach ($subsubcategory->threads as $thread)
            ...
        @endforeach
    @endforeach
@endforeach
```

...should work.

**Comment by Denoder** [comment]
This is my current index.blade.php
https://gist.github.com/Teranode/b4f8c864d38b8b58cbae

how would i show it in the front?

**Comment by Riari** [comment]
Sorry, I meant to say `index.blade.php`

As long as you nest the loops as in my example then it should work.

**Comment by Denoder** [comment]
i still dont get it

**Comment by Riari** [comment]
Well, you don't need to do it EXACTLY as in my example, just make sure you have a `@foreach ($subcategory->subcategories as $subsubcategory)` loop somewhere inside your `@foreach ($category->subcategories as $subcategory)` one, and then somewhere in your `@foreach ($subcategory->subcategories as $subsubcategory)` loop you can add a `@foreach ($subsubcategory->threads as $thread)` one.

I'm not going to edit your index view for you because I have no idea exactly where you want to show the threads, or how you want to format them.
