### ISSUE TITLE
forum.general.php

### ISSUE THREAD

**Issue by DevHoracioRodriguez** [Riari/laravel-forum#324]
Hello Riari

Changing forum.general.php, I found out that:
1. display_trashed_posts = false is ignored. Soft-deleted posts are always shown.
2. categories doesn't paginate as indicated value.

Thank you

**Comment by Riari** [comment]
Hi,

The category pagination option is actually redundant at this point and I should remove it. It used to apply to the category index API endpoint, but that's not the case as of version 5. The reason categories aren't paginated is because they can be arranged in a tree structure, so if you do that, pagination wouldn't make sense because you'd have an incomplete structure unless you fetch every page (which defeats the purpose of paginating in the first place). It wouldn't bring much value when using a flat structure either, as the total number of categories in a typical forum doesn't get much above a few dozen.

Regarding `display_trashed_posts`: the only reason this option exists is because policy checks only apply to authenticated users. For unauthenticated users, they always return `false`. Basically:
  * If `true`: always display trashed posts; skip policy checks.
  * If `false`: defer to the policy checks (always `false` for guests, otherwise `true` depending on what the `ForumPolicy::viewTrashedPosts` policy method returns).

I should probably update the docs and comment block in the config to include that explanation.

Thanks for bringing these up since I have some work to do there, and I hope this clears up any confusion!
