### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by Temian1** [Riari/laravel-forum#334]
Can you please implement a share button to all threads

**Comment by Riari** [comment]
A share button for what? Do you mean for social media? I would prefer not to provide that by default because it's very subjective (not just in terms of whether to show a share option, but which sites it should support sharing to).

I think this is easy enough to do with some changes to the [thread.show](https://github.com/Team-Tea-Time/laravel-forum/blob/5.0/views/thread/show.blade.php) view if you'd like to override the view in your project to add the button yourself.
