### ISSUE TITLE
Overriding Routes

### ISSUE THREAD

**Issue by t-omw** [Riari/laravel-forum#350]
Hi, I would like to apply auth middleware to these routes stored in vendor/riari/laravel-forum/routes/web.php:

Route::get('/', ['as' => 'index', 'uses' => 'CategoryController@index']);

Route::get('recent', ['as' => 'recent', 'uses' => 'ThreadController@recent']);

Route::get('unread', ['as' => 'unread', 'uses' => 'ThreadController@unread']);

    Route::get('/', ['as' => 'thread.show', 'uses' => 'ThreadController@show']);
    Route::get($prefix['post'].'/{post}', ['as' => 'post.show', 'uses' => 'PostController@show']);

Obviously files in vendor should not be edited, so how can I apply the middleware to these routes? all other routes in this file have ->middleware($authMiddleware) and are working as required its just some don't have it applied.

**Comment by Riari** [comment]
Hi,

I assume you want to do this so that your entire forum requires authentication to view, is that right? I'll have to think about ways to do that cleanly. The auth middleware isn't applied to those routes out of the box because in most cases, users want the forum index and at least some of the content to be publicly visible (without logging in). I totally understand if that's not your case though.

For now, I would suggest you override those specific routes with your own definitions, allowing you to add whatever middleware you like. Alternatively, you could define a new service provider, load it after the package service provider, and use it to resolve your application's router so you can add the middleware programmatically.

I hope that's of some use! I'll get back to you if I think of a better approach.

**Comment by Riari** [comment]
By the way, just to note, the `thread.show` and `post.show` routes don't need the auth middleware as long as you set all of your categories to be private. Setting a category to private triggers an authorization check when trying to access the category or anything inside it, which in turn requires authentication. Threads shown when viewing the `recent` and `unread` are automatically filtered on this basis.

**Comment by t-omw** [comment]
Hi thanks for the response :)

Its because in my case it is a part of my application rather than the application being a forum itself as now unauthenticated users are able to visit the forum index, exposing the nav bar of my application which would reveal super secret information of what the application offers lol. I will attempt overriding the routes, much appreciated
