### ISSUE TITLE
Handle users with UUID as id column

### ISSUE THREAD

**Issue by rexwebmedia** [Riari/laravel-forum#356]
I'm using uuid as the user id, and getting the following error. How can I solve the error.

![image](https://github.com/Team-Tea-Time/laravel-forum/assets/63487995/81c69b4d-e9cd-4a94-91cc-ada602c51f7e)

**Comment by Riari** [comment]
Hi,

Unfortunately the package doesn't support applications where the user table uses anything other than an int type for IDs due to the fact it stores user references in int columns. It's possible to add support for UUIDs, but it would require changes to the migrations so I need to think about how to approach that.

I'll keep this issue open until I have an update.

**Comment by Riari** [comment]
Sorry for the wait. I've just released [5.6.2](https://github.com/Team-Tea-Time/laravel-forum/releases/tag/5.6.2), which adds support for any column type for the user model's primary key.

If you still need this, to take advantage of it, you'll need to either delete the forum tables and migrations in order to run the updated ones (make sure you re-publish them first), or manually modify the following columns to match your user table PK type (presumably `char(36)` if you're using UUIDv4s):

* `author_id` in `forum_threads`
* `author_id` in `forum_posts`
* `user_id` in `forum_threads_read`
