### ISSUE TITLE
Refactor Validation

### ISSUE THREAD

**Issue by Denoder** [Riari/laravel-forum#36]
So how does the validation work?

I was testing it, and when submitting data, it would just redirect to the same page without giving off errors.

Then when i remove the validation, the submission passed through perfectly without any errors.

Also note that I pretty much am trying to branch off the package now because, I have no use for the API references. (Not saying that it sucks, i mean it is a package, however i'm just trying to use a forum)

**Comment by Riari** [comment]
You're probably missing some of the latest changes in the views. I fixed an
issue with them a few days ago that meant only non-validation alerts showed
up, even though validation errors were present in the session.

**Comment by Riari** [comment]
As for your comment about the API, that makes no sense. You won't gain anything by ripping parts of the package out and leaving out the API, because that's an integral part of it.

Viewing, creating and editing categories, threads and posts (where applicable) doesn't require the API, but every other action, like moving/locking/pinning threads, does. It's not just there for consumption outside of your domain (although that is possible, if for example you wanted to pull forum data via the API to display on another site).

I'm actually reworking the JS implementation that ships with the package to use [vue.js](http://vuejs.org/), which will make use of the API to enable tighter coupling between the frontend and data persistence. The JS is written directly in the views so you will be able to easily throw it out and replace it with your own implementation if you want, but you won't want to throw out the entire API if you want everything to work.
