### ISSUE TITLE
Can't Install on Fresh Installation of Laravel 11

### ISSUE THREAD

**Issue by earthly-pixel** [Riari/laravel-forum#368]
I tried to install v6.0 in fresh installation of Laravel 11

```
composer require riari/laravel-forum:^6.0 -W
```

and got dependency error like :

```
Problem 1
    - Root composer.json requires riari/laravel-forum ^6.0 -> satisfiable by riari/laravel-forum[6.0.0, ..., 6.0.6].
    - riari/laravel-forum[6.0.0, ..., 6.0.6] require kalnoy/nestedset v6.x-dev -> found kalnoy/nestedset[v6.x-dev] but it does not match your minimum-stability.
```
Do i need to install dev dependecy for this?

**Comment by Riari** [comment]
Hi,

This is due to a temporary dependency on a branch in kalnoy/nestedset (which implicitly lowers the stability to `dev`) because there was no Laravel 11 compatible release for it when I prepared Laravel Forum 6 for release.

I believe there is a new stable version now that I can switch to, so I'll do that tonight and push a new release with it. You should be able to install the package once that's done. I'll notify here when the new release is out.

**Comment by Riari** [comment]
I've just pushed a new release, [6.0.7](https://github.com/Team-Tea-Time/laravel-forum/releases/tag/6.0.7). You should now be able to install the package without having to lower your `minimum-stability`.
