### ISSUE TITLE
Add rating to threads and posts

### ISSUE THREAD

**Issue by geras332** [Riari/laravel-forum#372]

**Comment by geras332** [comment]
Or I can extend the Thread, Post model myself?

**Comment by Riari** [comment]
You can't extend the models in a way that makes the package use your versions instead of the originals, but you can extend them for use in your own controllers, views, etc. You can override specific package routes or views, so it's possible to implement a rating feature by doing that as well as extending the models to add whatever you need for your logic.

**Comment by geras332** [comment]
Thanks a lot! love you
