### ISSUE TITLE
Thread Count + Post Count for nested categories + Getting Latest Thread from both nested levels

### ISSUE THREAD

**Issue by Denoder** [Riari/laravel-forum#39]
What would i have to do to get the total count of threads an posts in a category with subcategories?

My Categories are nested as such:

Main Category (No Threads Allowed in here, so its just a base)
  Category (Actual Category - 2nd level)
    Subcategory (3rd level of nested category according to the package)

Here's a screenshot too.
![](http://i.imgur.com/8RiPAOL.png)

This is also another problem with grabbing the latest active thread from both the 2nd and 3rd level nested category because it would only show the latest thread from the 2nd level category which is the actual category.

**Comment by Riari** [comment]
A recursive function to get a category's deepest category would solve this - I'll look into that for v3. Will probably make it have an optional argument to specify the limit (with a high default).

The only problem with this is the impact on the database since it would potentially result in a lot of queries, albeit small ones. I'll be spending some time on v3 to make it as optimized as possible out of the box.
