### ISSUE TITLE
View [category.index] not found.

### ISSUE THREAD

**Issue by AlphaGX** [Riari/laravel-forum#392]
Trying to setup a new project, but I can't get it to work properly.
I saw that dependabot failed to bump laravel/framework to 11.31.0 so I even tried with laravel 11.2.0 and 11.0.0 but to no avail.

The error I get is when visiting /forum _View [category.index] not found_.

I could fix the error by `mv ressources/forum/tailwind-livewire/view resources/views/vendor/forum`
Then `mv resources/views/vendor/forum/pages/* resources/views/vendor/forum/`

After that, when visiting /forum I don4t get any error, but just a blank page with 3 gray circle (kinda like a loading animation)

Here is a minimal reproduction setup
```
composer create-project laravel/laravel="11.0.0" forum
cd forum
composer require livewire/livewire
composer require riari/laravel-forum:^6.0
php artisan forum:preset-install livewire-tailwind
# Select yes when it ask to install
npm i @melloware/coloris alpinejs date-fns laravel-echo nested-sort tailwindcss
php artisan vendor:publish
# here I publish all available
php artisan migrate
php artisan serve
```

OS: `Linux legion 6.11.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 17 Nov 2024 16:06:17 +0000 x86_64 GNU/Linux`
php version: `PHP 8.3.14 (cli) (built: Nov 19 2024 17:18:20) (NTS)`
composer version: `Composer version 2.8.3 2024-11-17 13:13:04`

**Comment by Riari** [comment]
Hi,

I think this is because the `forum.frontend.preset` config value is still set to `blade-tailwind` (the default). You need to change it to `livewire-tailwind`. The preset install command displays a note regarding this once it completes - maybe I'll see if I can make it automate this step :)

Let me know if that solves the problem for you.

**Comment by AlphaGX** [comment]
Yes thank you that did the trick.
I also had to add resources/forum/livewire-tailwind/css/forum.css and resources/forum/livewire-tailwind/js/forum.js to the vit.config.js file.

However now that the page load there is no css (I think).
Just a blank page with a few links (Laravel Forum, Index, Recent threads, Log in, Register, Index, Index)

I tried with a new project and the default ui preset and it was the same.

Maybe I need to configure tailwind ?

Sorry to bother you so much...

**Comment by AlphaGX** [comment]
Okay I guess I figured it out.
I installed tailwind following this guide
[https://tailwindcss.com/docs/guides/laravel](https://tailwindcss.com/docs/guides/laravel)

Then I copied 
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```
in `resources/css/app.css`

**Comment by Riari** [comment]
Glad you got it working :)

Yes, you do need to install Tailwind for the presets that use it, but you shouldn't need to add those directives to `resources/css/app.css` because they're already in the forum preset's CSS. That does highlight a missing step in the installation docs - you need to include the preset's CSS and JS paths in `vite.config.js` so that Vite processes them when you run `npm run build`:

```
'resources/forum/livewire-tailwind/css/forum.css',
'resources/forum/livewire-tailwind/js/forum.js',
```

I'll update both the preset installer and the docs to make all of this clearer and maybe automate more of it.
