### ISSUE TITLE
Need help overriding Controllers

### ISSUE THREAD

**Issue by Denoder** [Riari/laravel-forum#40]
I'm trying to override the create and store method in the Thread Controller. I extended it, and made a create method, but it doesn't work. The reason for this is because i disabled the integrated permissions and would like to use my own and the one you have is directly in the controller file.

**Comment by Riari** [comment]
Assuming you're talking about v3, no, there's no permission handling directly in the controllers. What you're referring to is probably the threadsAllowed check, which isn't permission handling per se but checks to see if the category specified in the request accepts threads or exists only as a category (i.e. not a forum).

But if you're overriding the controller then you can override that method however you like. The original method will be replaced by yours unless you explicitly call it.

The permission handling, on the other hand, is triggered by middleware before the request hits the controllers. If you want to completely disable the permissions, you can do so in [config/permissions.php](https://github.com/Riari/laravel-forum/blob/l5-refactor/config/permissions.php) or remove the middleware registration in the service provider: https://github.com/Riari/laravel-forum/blob/l5-refactor/src/ForumServiceProvider.php#L102-L106

**Comment by Denoder** [comment]
i have already disabled the permissions in the config, as stated in my earlier post.
The problem now is using my own permissions on the controller functions, because right now its insecure and "everyone" [including guests] can post anything.

I need to know how to put permissions in the controller witouht having to go directly in the vendor file and changing the controllers there. I have extended the ThreadController, but i dont know what to do.

**Comment by Riari** [comment]
You didn't specify _how_ you disabled the permissions, so I gave you a couple of options anyway.

Anyway, at this point I'd just be teaching you PHP/Laravel. What you're doing is really independent of the forum, other than using its events or routes to implement your permissions.

I suggest you read up on different ACL techniques in Laravel and pick one. I do something very similar to this in one of my other projects: http://heera.it/laravel-5-0-acl-using-middleware, only I apply the middleware globally and use a combination of route names and [entrust](https://github.com/Zizaco/entrust) (to provide the roles and permissions).

**Comment by Denoder** [comment]
just checked the integration config and i saw that i could change the controllers, didnt see that <_<

run into a different problem:

Type error: Argument 1 passed to Riari\Forum\Http\Controllers\ThreadController::__construct() must be an instance of Riari\Forum\Models\Thread, none given, called in /home/public_htmlb/app/Http/Controllers/Frontend/ThreadController.php on line 35

**Comment by Riari** [comment]
Can't really help without seeing your version of the controller, but if you're overriding the parent __construct() then you need to explicitly pass an instance of the Thread model to it because Laravel's service container won't take care of intermediate dependency injection.

Edit: that might only apply if you're calling `parent::__construct()` without args - I can't remember. But if you share your controller in a gist or on http://laravel.io/ then I'll take a look.

**Comment by Denoder** [comment]
before i start getting stupid what parameters could i pass in the callback? for integration?
like for instance could i do this?

```
        'thread' => [
            'show' => function ($user, $parameters = [])
            {
                return true;
            },
            'create' => function ($user, $parameters = [])
            {
                if(! access()->can('can_manage_forums_new_thread')) {

                    return redirect('/');
                }

                return true;
            }
        ],
```

because i did try doing that and nothing happened :|

if i change the redirect to false; i get;
HttpException in Application.php line 882:
which basically shows the 403 forbidden error page i haven't set up, but i'd like to just redirect.

and sorry if the replies come later than usual, my ISP is having outages.

**Comment by Riari** [comment]
The callbacks need to return a bool, so yes, when your condition passes it should return false.

The 403 response is given when the permission check doesn't pass (i.e. access is denied). It occurs in the [CheckPermission middleware](https://github.com/Riari/laravel-forum/blob/l5-refactor/src/Http/Middleware/CheckPermissions.php). In v2, that behaviour is easily changeable via another callback, which I took out during refactoring to slim things down - but if you need to redirect then I'll consider reinstating it.

Until then, your best bet would be to write your own version of the middleware and register that instead of the default one in ForumServiceProvider.php (which would obviously mean extending that and changing the namespace in your app config).

**Comment by Denoder** [comment]
redirecting would be nice.

**Comment by Riari** [comment]
See the latest commit (just pushed). I have reinstated the access_denied callback in the permissions.php config file, allowing you to return whatever kind of response you like. It's untested so I can't guarantee it works, but it should.

**Comment by Denoder** [comment]
thanks it works.
