### ISSUE TITLE
Write a dispatcher to consume the API internally

### ISSUE THREAD

**Issue by Riari** [Riari/laravel-forum#45]
[Updated] The API should remain part of the core and possible to consume both internally and externally. To support this for the default frontend options, a dispatcher class should be introduced.

**Comment by atrakeur** [comment]
Instead of taking the optionnal API front-end, what about takibg it thé other way around?

Maybe you can do an API package that does all the fubctionnality. Then on top of that add a front-end.

This way, the frontend can be anything: a laravel app, angular app or maybe even a native app. All the core functionnality is keep inside the core package. And the end user can choose a front-end based on needs.

Just a quick suggestion anyway, doing an optionnal API package that plug into a core package is less extensible but also less complicated.

**Comment by Riari** [comment]
Hmm, I hadn't thought of it like that. It sounds like an idea worth exploring, but I must admit I'm not really convinced about the benefit we'd gain from doing this. Could you elaborate and maybe give more examples?

The only reason I say that is because the API currently only exists to provide a RESTful HTTP interface, and is actually quite lean. Based on my current plans, once it's finished, it would re-use the models and authorisation that already exist in the main package - those are the only two components that would be used in common. The REST API controllers handle requests and responses slightly differently to the regular frontend ones, especially in regards to request validation (see examples in the API's [Http/Controllers/PostController.php](https://github.com/Riari/laravel-forum-api/blob/master/src/Http/Controllers/PostController.php)).

I'm not wishing to dismiss the idea of course - I might just be looking at it from the wrong angle. If you could give me a rough "map" of how you'd see the various packages/components fitting together, that would be awesome.

**Comment by atrakeur** [comment]
Well basically the package with the API become the core of the forum. It regroup all the core functionnality (ie: how the forum do things).
On top of that, there is a package for the front end that use the API to do things, but in a pretty way (here comes client side validation).
The frontend package call the API when it need to (post a message, delete a topic, etc) and present the responce in a pretty way.

The benefit is that we are sure the API expose all the functionnality needed by the app to behave normaly. 
Also, because our frontend use the same communication interface that any third party will use, we are sure to spot bugs before any other third party. 
Finally, units tests are quite simplified too because we can just write tests for the API and it will validate both functionnality and backward compatibility with third party app at the same time and reduce the amount of testing code needed. 

It's a sort of service oriented architecture and it's quite common in very big apps.

Anyway I'm not sure the benefits are worth the additionnal complexity so the choice is your.

**Comment by Riari** [comment]
Okay, I think I follow now. That's actually not far off what I started to do, only I was building everything in the current package rather than splitting it up. My intention was to make it work out of the box using the API, but doing so meant writing a lot of frontend code (more than I anticipated) and dropping almost all of the views in favour of vue.js components, so I felt like it started to become too opinionated.

So that's why I began separating the API in order to revert back to a very basic frontend implementation that makes no assumptions about what kind of JS framework to use (if any), i.e. using minimal JS/no AJAX/regular forms. That in itself brings a new problem; the REST API is useless for that purpose, so something (whether it's the core package or another one) needs to provide conventional Laravel controllers that return standard views.

That said, it would make sense for that group of controllers and the REST API to both use some kind of common underlying API, but I'm not sure yet what the appropriate technique would be. Maybe the repository pattern, maybe something else.

I'll definitely think about this. I'm currently focusing on a client project, but will move back onto this at the beginning of October.

I really appreciate the input, by the way :)

**Comment by atrakeur** [comment]
Frontend can be made of laravel controllers and views of course.
All the point is that Frontend controllers are going to call API controllers to fetch information, and then return classics views.
When doing it like that is that the "common underlying API" between the frontend and the API is the API itself.

**Comment by Riari** [comment]
Well, all of the API methods are currently written to return an instance of `Illuminate\Http\JsonResponse`, and I'm not keen on the idea of calling controller methods from another controller.

I can see what you mean, though. I think it's just going to require a bit of reorganisation to abstract the data fetching and persistence into dedicated classes. That may or may not work out, because as I said, I did at one point proceed with implementing a repository pattern and later found that it didn't offer much over simply using the models directly in both sets of controllers.

It's very possible that I implemented it badly though, so it definitely bears some reconsideration.

**Comment by flamerohr** [comment]
My post depends on how much logic is in the API calls, like permissions/validation, I guess?
The repository pattern is primarily to abstract the model layer so that it doesn't matter if your were using eloquent or some kind of nosql package model.

I think a kind of gateway pattern is more what you're looking for, so the gateway classes are your api classes where all the business and validation logic is put into.
Then you have two types of controllers, which can be separated to two packages.
- The api controllers, transfers the input to the gateway classes and then returns the gateway output as responseJson. Very thin controllers.
- The app controllers, takes input if any, calls any gateway classes and then returns view that is necessary.

It has the benefit to be open to whatever people want the (app controllers) frontend to be, and keep it as two packages with the app package dependent on the API package.
Drawback is obviously structural complexity and a bit of programming overhead with the extra layer. 

What do you think?

**Comment by Riari** [comment]
Sounds good. I need to do some research on this before I dive back into the code, but I'll take a shot at it in the next few weeks. :)

**Comment by Riari** [comment]
Updated. After some research and deliberation, I realised Laravel makes it quite easy to dispatch routes internally without much overhead, so I'm going to incorporate the API back into the main package and write a dispatcher to support that.

That means the core, API and supporting code will all be part of the main package, while the frontend implementations can remain in their own packages and do their data querying/persistence via the API. I think this is consistent with the original suggestion from @atrakeur.

Thanks for the input on this :)
