### ISSUE TITLE
Authentification with Sentinel

### ISSUE THREAD

**Issue by madita** [Riari/laravel-forum#62]
Me Again...
Problem ist I don't have any buttons to create categories and after I take the route directly forum/category/ create I get 
MethodNotAllowedHttpException in RouteCollection.php line 219:

I am not sure if I am missing this, because I can't find it
Illuminate\Foundation\Auth\Access\AuthorizesRequests
And how I can install it or do I have trouble, because of the Sentinel package.

**Comment by Riari** [comment]
There's no GET route to provide a page with a category creation form, although you could create one if you wanted. `/forum/category/create` just requires a POST request with a `title`, a `description` (optional), a `category_id` (to place the category under - 0 for none), and 2 booleans - `enable_threads` and `private`.

Edit: To clarify, your problem does appear to be auth related as there would otherwise be a "Create category" panel visible when viewing the forum index. Just explaining what the route you mentioned is for.

Anyway, I've never used Sentinel myself but I suspect that's the issue; the forum uses Laravel's built-in auth interface and if Sentinel doesn't plug into that, it won't pick up your user sessions. 

If that's the case, the workaround would be to fill that gap in so that Sentinel sessions are mirrored as Laravel ones, or otherwise accessible to Laravel's auth. This will need some investigation, so anything you find out in the meantime could be very useful.

**Comment by madita** [comment]
OK I see. In Version 2 of the Forum I just changed the ForumController and added "use Sentinel". So I try to find a workaround.

**Comment by Riari** [comment]
Yeah, unfortunately it's not that simple anymore due to the forum now using Laravel Authorisation. That automatically picks up the current Laravel user and won't work with Sentinel sessions unless there's some integration for it.

I can say from past experience in integrating custom authentication with Laravel that it probably entails implementing a custom UserProvider class and registering a custom auth driver for it. This thread offers some insight into that: http://laravel.io/forum/11-04-2014-laravel-5-how-do-i-create-a-custom-auth-in-laravel-5

An alternative would be to drop Sentinel and implement your auth/user features using vanilla Laravel 5.1 instead, which I realise probably isn't desirable if you've been using it for a while and have a lot of code doing Sentinel calls. However, the user and auth features in Laravel 5/5.1 make it a lot easier than before to implement things like account confirmation, password reset, etc, and implementing user roles/permissions is also pretty quick to do with a few models.

**Comment by Screpuh** [comment]
Hey @madita, 

Did you find a solution for this?

Thanks!

**Comment by m3rg** [comment]
I created a middleware and put the following and it is working for me but I am not sure if that is a good solution.

``` php
if(Sentinel::check() && !Auth::id()) {
    Session::put(Auth::getName(), Sentinel::getUser()->id);
}
```
