### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by morloderex** [Riari/laravel-forum#89]
Hello Riari

The documentation doesn't say anything about request scopes yet, and because of this the documentation is quite redundant.

**Comment by Riari** [comment]
Elaborate please. Is this about the API docs specifically?

**Comment by morloderex** [comment]
Well, for instance how should the developer know how to make requests with the with-scope if they haven't looked at the fronted package first?

**Comment by Riari** [comment]
Ah, yeah. There are a few areas that aren't covered comprehensively in the
docs yet, that being one of them and another being the policy methods. It's
only the first iteration, so they won't be fully comprehensive yet.

I'll update them when I have time, but they do refer to the frontend as a
point of reference, and you mentioned it yourself - so that's an ideal
place to look in the meantime ;)

**Comment by morloderex** [comment]
Yeah, but it's kinda the only place to look right now, and if I where to add additional scopes to it how would I do such a thing?

It current docs does not say how you use this package but more what's included in it.

**Comment by morloderex** [comment]
Yeah, but it's kinda the only place to look right now, and if I where to add additional scopes to it how would I do such a thing?

It current docs does not say how you use this package but more what's included in it.

**Comment by morloderex** [comment]
Sorry for reposting.

**Comment by Riari** [comment]
The current docs go well beyond that. I'm not sure what makes you think otherwise - they cover installation, configuration, the available API endpoints and a few other things.

Also, some things fall outside the scope (heh) of these docs as they're more Laravel business than laravel-forum - such as adding your own model scopes. You would do that just like you would in any other Laravel project, so I won't cover that kind of thing in the docs.

Anyway, as I said before, I will update the docs when I have time to do so. That's why they're in [version control](https://github.com/Riari/laravel-forum-docs), so I can expand and update them incrementally (and accept contributions). The absence of this one topic doesn't make them "redundant", and the frontend package makes solid reference material until I can work on the docs more.
