### ISSUE TITLE
Unicode slugs

### ISSUE THREAD

**Issue by ikanc** [Riari/laravel-forum#92]
There is a problem with unicode slugs (hebrew/arabic) while using Str::slug($this->title);
The default Str::slug returns null on unicode characters, and therefore, we cannot have categories/posts in Unicode.

**Workaround (how I fixed it)** - return Str::slug(urlencode($this->title));
**Better fix** - don't use the title for the slug, or allow a config for "no slug, only numeric"
**Much better fix** -  create a slug function that will replace urlencode

**Comment by Riari** [comment]
Thanks - I agree with your suggestions. After some reading, to support URL slugs for all of the currently supported languages seems like a complicated issue. I might try using cocur/slugify with some additions, as per this: https://github.com/cocur/slugify/issues/47#issuecomment-136085239

Would you be willing to try that out and let me know how well it works for you?

**Comment by Riari** [comment]
[laravel-forum-frontend 1.0.4](https://github.com/Riari/laravel-forum-frontend/releases/tag/1.0.4) now includes a new `Forum::slugify()` method, which is used by `Forum::route()` to generate slugs. It still uses str_slug($title), but can be overridden since the utility class can be specified in config.
