### ISSUE TITLE
Compatibility issue with Laravel 5.0

### ISSUE THREAD

**Issue by javidsapand** [Riari/laravel-forum#96]
Recently I installed riari/laravel-forum:~3.0 package into my Laravel 5.0 project, but gave me errors  at end of installation in **php artisan clear-compiled** : **Class Illuminate\Contracts\Auth\Access\Gate does not exist** and **Script php artisan clear-compiled handling the post-update-cmd event returned with an error**.
when i installed the package v-3.0 into laravel 5.1, and package v-2.4.9  to laravel 5.0, it worked.
I searched but i couldn't find the solution for it, and i still need  riari/laravel-forum:~3.0 for my project in laravel 5.0.

**Comment by Riari** [comment]
It requires Laravel 5.1 because of the Gate class, so you'll need to [upgrade your project](https://laravel.com/docs/5.1/upgrade#upgrade-5.1.0) (a lot of those steps are optional depending on what parts of Laravel your project uses).

Composer shouldn't actually let you install it without Laravel 5.1, so I'll fix the composer.json deps list. I'll update the readme and docs to make this requirement clearer as well.

**Comment by javidsapand** [comment]
but how about v-2.4.9, is it works perfectly for laravel 5.0?

**Comment by Riari** [comment]
Yes, 2.X doesn't use Authorization.

**Comment by javidsapand** [comment]
Thank you very much
